### ISSUE TITLE
Key 'uid' is not in the LDAPEntry error with Active Directory

### ISSUE THREAD

**Issue by skokhanovskiy** [caltechads/nginx-ldap-auth-service#1]
Can't integrate module with Microsoft Active Directory.

After submitting LDAP credential I'm getting 'Internal Server Error' with log

```
2024-04-08 09:57:40,325 172.23.0.3:59960 - "POST /auth/login HTTP/1.0" 500
2024-04-08T09:57:40.328695Z [error    ] Exception in ASGI application
 [uvicorn.error] 
Traceback (most recent call last):
  File "/ve/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ve/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ve/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/ve/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/ve/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/ve/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/nginx_ldap_auth/app/middleware.py", line 111, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/ve/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/ve/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/ve/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/ve/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/ve/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/ve/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/ve/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/ve/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ve/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nginx_ldap_auth/app/main.py", line 176, in login_handler
    if await form.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/app/nginx_ldap_auth/app/forms.py", line 59, in is_valid
    if user := await User.objects.get(cast(str, self.username)):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nginx_ldap_auth/app/models.py", line 232, in get
    return self.model.parse_ldap(results[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nginx_ldap_auth/app/models.py", line 267, in parse_ldap
    'uid': data['uid'][0],
           ~~~~^^^^^^^
KeyError: "Key 'uid' is not in the LDAPEntry."
```

Configuration snippet from my compose file:

```yaml
  ldap-auth-service:
    image: caltechads/nginx-ldap-auth-service:latest
    hostname: ldap-auth-service
    ports:
      - 8888:8888
    environment:
      HOSTNAME: '0.0.0.0'
      LDAP_URI: ldap://dev-dc00
      LDAP_BASEDN: DC=local,DC=domain,DC=com
      LDAP_USERNAME_ATTRIBUTE: sAMAccountName
      LDAP_BINDDN: CN=ldap-vieweri,OU=ServiceAccounts,OU=Service,DC=local,DC=domain,DC=com
      LDAP_PASSWORD: "${LDAP_PASSWORD:?}"
```

The problem code below

https://github.com/caltechads/nginx-ldap-auth-service/blob/master/nginx_ldap_auth/app/models.py#L264-L270

May be instead of hard-coded `uid` here should be used a value form the `LDAP_USERNAME_ATTRIBUTE`?

**Comment by cmalek** [comment]
I am so sorry that I somehow missed your issue!  You're exactly right -- I missed a spot where I should have used `LDAP_USERNAME_ATTRIBUTE`.  I will fix and release a new version.

Thank you very much for your submission.

**Comment by cmalek** [comment]
I've released a fix for this in v2.1.3.  Could you give it a try if you are still interested?
